In [1]:
import pandas as pd
from sklearn.neighbors import LocalOutlierFactor

df = pd.read_csv("C:/Users/Alperen Arda/OneDrive/Desktop/GitHub/FlightDelayCancellation/src/semi_clean_data.csv")
df.head()

C:\Users\Alperen Arda\AppData\Local\Temp\ipykernel_13448\3621268061.py:4: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/Alperen Arda/OneDrive/Desktop/GitHub/FlightDelayCancellation/src/semi_clean_data.csv")

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,...,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY
0,1,1,4,AS,98,N407AS,ANC,SEA,5,2354.0,...,15.0,205.0,194.0,169.0,1448,404.0,4.0,430,408.0,-22.0
1,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,2.0,...,14.0,280.0,279.0,263.0,2330,737.0,4.0,750,741.0,-9.0
2,1,1,4,US,840,N171US,SFO,CLT,20,18.0,...,34.0,286.0,293.0,266.0,2296,800.0,11.0,806,811.0,5.0
3,1,1,4,AA,258,N3HYAA,LAX,MIA,20,15.0,...,30.0,285.0,281.0,258.0,2342,748.0,8.0,805,756.0,-9.0
4,1,1,4,AS,135,N527AS,SEA,ANC,25,24.0,...,35.0,235.0,215.0,199.0,1448,254.0,5.0,320,259.0,-21.0

In [2]:
df.isnull().sum()

MONTH                  0
DAY                    0
DAY_OF_WEEK            0
AIRLINE                0
FLIGHT_NUMBER          0
TAIL_NUMBER            0
ORIGIN_AIRPORT         0
DESTINATION_AIRPORT    0
SCHEDULED_DEPARTURE    0
DEPARTURE_TIME         0
DEPARTURE_DELAY        0
TAXI_OUT               0
WHEELS_OFF             0
SCHEDULED_TIME         0
ELAPSED_TIME           0
AIR_TIME               0
DISTANCE               0
WHEELS_ON              0
TAXI_IN                0
SCHEDULED_ARRIVAL      0
ARRIVAL_TIME           0
ARRIVAL_DELAY          0
dtype: int64

In [3]:
from preprocess_flights import DataPreprocessor

feature_list = ['DISTANCE', 'ARRIVAL_DELAY']

preprocessor = DataPreprocessor()

preprocessor.fast_process(df, feature_list=feature_list)

Fast Processing:   0%|                                    | 0/5 [00:00<?, ?it/s]

Dropping unnecessary features...

Fast Processing:  20%|█████▌                      | 1/5 [00:00<00:01,  2.72it/s]

Encoding categorical variables...

Fast Processing:  40%|███████████▏                | 2/5 [00:02<00:04,  1.50s/it]

Analyzing single-variable outliers...

Fast Processing:  60%|████████████████▊           | 3/5 [00:03<00:02,  1.00s/it]

Analyzing multi-variable outliers...

c:\Users\Alperen Arda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_lof.py:322: UserWarning: Duplicate values are leading to incorrect results. Increase the number of neighbors for more accurate results.
  warnings.warn(
Fast Processing:  80%|██████████████████████▍     | 4/5 [00:56<00:21, 21.64s/it]

Toplam Veri: 5714008, Aykırı Olmayan Veri: 5542584
Dropping missing values...

Fast Processing: 100%|████████████████████████████| 5/5 [00:56<00:00, 11.37s/it]

Fast processing completed!

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DISTANCE,SCHEDULED_ARRIVAL,ARRIVAL_DELAY
0,1,1,4,0.030003,1230,0.002768,0.019285,5,1448,430,-22.0
2,1,1,4,0.033991,1300,0.025462,0.017296,20,2296,806,5.0
3,1,1,4,0.124770,729,0.033602,0.011955,20,2342,805,-9.0
4,1,1,4,0.030003,1259,0.019282,0.002768,25,1448,320,-21.0
5,1,1,4,0.152306,889,0.025462,0.019451,25,1589,602,8.0
...,...,...,...,...,...,...,...,...,...,...,...
5714001,12,31,4,0.045860,1117,0.033847,0.016029,2359,1626,530,-11.0
5714003,12,31,4,0.045860,1118,0.033602,0.018385,2359,2611,819,-26.0
5714005,12,31,4,0.045860,423,0.016042,0.004278,2359,1598,440,-8.0
5714006,12,31,4,0.045860,1027,0.019169,0.004278,2359,1189,340,-10.0
5714007,12,31,4,0.045860,1176,0.016042,0.000232,2359,1576,440,2.0